//
//  CompetenceCollaborateurPresenter.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 6/2/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CompetenceCollaborateurPresentationLogic
{
    func presentSomething(response: CompetenceCollaborateur.Something.Response)
    func showCompetenceCollaborator(responses: CompetenseResponse,skillsLabel:[String: String])
}

class CompetenceCollaborateurPresenter: CompetenceCollaborateurPresentationLogic
{
    weak var viewController: CompetenceCollaborateurDisplayLogic?
    
    // MARK: Do something
    func presentSomething(response: CompetenceCollaborateur.Something.Response)
    {
        let viewModel = CompetenceCollaborateur.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
//    MARK: -Afficher Competence Collaborateur
    func showCompetenceCollaborator(responses: CompetenseResponse,skillsLabel:[String: String]){
        viewController?.getDataCompetences(response: responses,skillsLabel: skillsLabel)
    }

}
