//
//  FormationCollaborateurWorker.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 5/8/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Promise

class FormationCollaborateurWorker
{
    func doSomeWork()
    {
    }
    
    
    func getListFormationCollaborateur(token : String) -> Promise<ResponseFormationCollaborateur> {
        return FormationAPI.showListFormationCollaborateur(token: token)
    }
    
}
