//
//  FormationWorker.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 4/27/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Promise


class FormationWorker
{
    func doSomeWork()
    {
    }
    
    func getListFormation(token : String) -> Promise<ResponseFormation> {
        print("hello !")
        return FormationAPI.showListFormationManager(token:token)
    }
    
    func getListFormationMesDemandes(token : String) -> Promise<ResponseFormation> {
        print("hello !")
        return FormationAPI.showListFormationManagerMesDemandes(token: token)
    }
    
    func showMyActions(token : String) -> Promise<ResponseAction>{
        print("ee")
        return FormationAPI.showMyActions(token: token)
    }
    
    func showCatalogueFormation(token: String) ->Promise<ResponseCatalogue>{
        print("worker Catalogue !")
        return FormationAPI.showCatalogueFormation(token: token)
    }
}
