//
//  FormationPresenter.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 4/27/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FormationPresentationLogic
{
    func presentSomething(response: Formation.Something.Response)
    func showFormationForValidation(response:ResponseFormation)
    func showFormationMyDemandes(response: ResponseFormation)
    func showMyActions(response: ResponseAction)
    func showCatalogue(response : ResponseCatalogue)
}

class FormationPresenter: FormationPresentationLogic
{
    weak var viewController: FormationDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Formation.Something.Response)
    {
        let viewModel = Formation.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func showFormationForValidation(response:ResponseFormation){
        viewController?.formationForValidationData(response:response)
    }
    func showFormationMyDemandes(response: ResponseFormation){
        viewController?.formationMyDemandesData(response: response)
    }
    func showMyActions(response: ResponseAction){
        viewController?.getActionsSessionData(response : response)
    }
    func showCatalogue(response : ResponseCatalogue){
        viewController?.getCatalogueData(response: response)
    }
}
