//
//  CatalogueFormationPresenter.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 5/12/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CatalogueFormationPresentationLogic
{
  func presentSomething(response: CatalogueFormation.Something.Response)
    func showCatalogue(response : ResponseCatalogue)
}

class CatalogueFormationPresenter: CatalogueFormationPresentationLogic
{
  weak var viewController: CatalogueFormationDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CatalogueFormation.Something.Response)
  {
    let viewModel = CatalogueFormation.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
    
    func showCatalogue(response : ResponseCatalogue){
         viewController?.getCatalogueData(response: response)
    }
    
    
}
