//
//  CatalogueFormationInteractor.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 5/12/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CatalogueFormationBusinessLogic
{
    func doSomething(request: CatalogueFormation.Something.Request)
    func showCatalogueFormation(token : String, page : Int, size: Int)
    func showListPopulation(token : String)
    func addCatalogue(token : String, param : TrainingRequestModelAdd)
}

protocol CatalogueFormationDataStore
{
    //var name: String { get set }
}

class CatalogueFormationInteractor: CatalogueFormationBusinessLogic, CatalogueFormationDataStore
{
    var presenter: CatalogueFormationPresentationLogic?
    var worker: CatalogueFormationWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: CatalogueFormation.Something.Request)
    {
        worker = CatalogueFormationWorker()
        worker?.doSomeWork()
        
        let response = CatalogueFormation.Something.Response()
        presenter?.presentSomething(response: response)
    }
    
    func showCatalogueFormation(token : String, page : Int, size: Int){
        worker = CatalogueFormationWorker()
        worker?.showCatalogueFormation(token: token, page : page, size: size).then(){
            formationCatalogue in
//            print(formationCatalogue.numberOfElements)
            self.presenter?.showCatalogue(response : formationCatalogue, page : page, size: size)
        }.catch{
            error in
            print(error)
        }
    }
    
    func showListPopulation(token : String){
        worker = CatalogueFormationWorker()
        worker?.showListPopulation(token: token).then(){
            population in
            print("in interractor formation Catalogue **************************")
            print(population)
            print("wwww")
            self.presenter?.showPopulation(response : population)
        }.catch{
            error in
            print(error)
        }
    }
    func addCatalogue(token : String, param : TrainingRequestModelAdd){
        worker = CatalogueFormationWorker()
        worker?.addCatalogue(token: token, param: param).then(){
            add in
            print("in interractor formation Catalogue **************************")
            print(add)
            print("wwww")
            let response : Bool
            self.presenter?.addingSuccess(response:true)
        }.catch{
            error in
            print(error)
            self.presenter?.addingFailure(response: false)
        }
    }
    
    
}
