//
//  CompanyLoginPresenter.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 7/5/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CompanyLoginPresentationLogic
{
  func presentSomething(response: CompanyLogin.Something.Response)
}

class CompanyLoginPresenter: CompanyLoginPresentationLogic
{
  weak var viewController: CompanyLoginDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CompanyLogin.Something.Response)
  {
    let viewModel = CompanyLogin.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
