//
//  FormationMyActionPresenter.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 5/12/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FormationMyActionPresentationLogic
{
  func presentSomething(response: FormationMyAction.Something.Response)
    func showMyActions(response: ResponseAction)
}

class FormationMyActionPresenter: FormationMyActionPresentationLogic
{
  weak var viewController: FormationMyActionDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: FormationMyAction.Something.Response)
  {
    let viewModel = FormationMyAction.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
    
    func showMyActions(response: ResponseAction){
        viewController?.getActionsSessionData(response : response)
    }
}
