//
//  AjouterCompetenceWorker.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 11/11/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Promise

class AjouterCompetenceWorker
{
  func doSomeWork()
  {
  }
    
    func getCompetenceLabelManager(token : String) -> Promise<[CompetenseLabelResponseElement]> {
        return CompetecenceAPI.showCompetenceLabelManager(token: token)
    }
    
    func getLevels(token : String, codeClassification : String) -> Promise<LevelResponse>{
        return CompetecenceAPI.showCompetenceLevels(token: token, codeClassification: codeClassification)
    }
    
    func addCompetenceByManager(token:String,params:[String:Any],code:String)->Promise<ResponseAddingCompetence>{
        return CompetecenceAPI.addCompetence(token: token, params: params, code: code)
    }
    
}
