//
//  AjouterCompetenceRouter.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 11/11/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AjouterCompetenceRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol AjouterCompetenceDataPassing
{
  var dataStore: AjouterCompetenceDataStore? { get }
}

class AjouterCompetenceRouter: NSObject, AjouterCompetenceRoutingLogic, AjouterCompetenceDataPassing
{
  weak var viewController: AjouterCompetenceViewController?
  var dataStore: AjouterCompetenceDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: AjouterCompetenceViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: AjouterCompetenceDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
