//
//  ProgrammeCatalogueInteractor.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 18/11/2020.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProgrammeCatalogueBusinessLogic
{
  func doSomething(request: ProgrammeCatalogue.Something.Request)
}

protocol ProgrammeCatalogueDataStore
{
  //var name: String { get set }
}

class ProgrammeCatalogueInteractor: ProgrammeCatalogueBusinessLogic, ProgrammeCatalogueDataStore
{
  var presenter: ProgrammeCataloguePresentationLogic?
  var worker: ProgrammeCatalogueWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ProgrammeCatalogue.Something.Request)
  {
    worker = ProgrammeCatalogueWorker()
    worker?.doSomeWork()
    
    let response = ProgrammeCatalogue.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
