//
//  ProgrammeCataloguePresenter.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 18/11/2020.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProgrammeCataloguePresentationLogic
{
  func presentSomething(response: ProgrammeCatalogue.Something.Response)
}

class ProgrammeCataloguePresenter: ProgrammeCataloguePresentationLogic
{
  weak var viewController: ProgrammeCatalogueDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ProgrammeCatalogue.Something.Response)
  {
    let viewModel = ProgrammeCatalogue.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
