//
//  CompetenceManagerRouter.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 6/21/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CompetenceManagerRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol CompetenceManagerDataPassing
{
  var dataStore: CompetenceManagerDataStore? { get }
}

class CompetenceManagerRouter: NSObject, CompetenceManagerRoutingLogic, CompetenceManagerDataPassing
{
  weak var viewController: CompetenceManagerViewController?
  var dataStore: CompetenceManagerDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: CompetenceManagerViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: CompetenceManagerDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
