//
//  CompetenceManagerPresenter.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 6/21/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CompetenceManagerPresentationLogic
{
    func presentSomething(response: CompetenceManager.Something.Response)
    func showCompetenceManager(response: CompetenseManagerResponse)
}

class CompetenceManagerPresenter: CompetenceManagerPresentationLogic
{
    weak var viewController: CompetenceManagerDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: CompetenceManager.Something.Response)
    {
        let viewModel = CompetenceManager.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    func showCompetenceManager(response: CompetenseManagerResponse){
        viewController?.getDataCompetenceManager(response:response)
    }
}
