//
//  CompetenceManagerWorker.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 6/21/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Promise


class CompetenceManagerWorker
{
  func doSomeWork()
  {
  }
    
    func getCompetenceManager(token : String) -> Promise<CompetenseResponse> {
        return CompetecenceAPI.showCompetenceManager(token: token)
    }
    func getCompetenceLabelManager(token : String) -> Promise<[CompetenseLabelResponseElement]> {
        return CompetecenceAPI.showCompetenceLabelManager(token: token)
    }
}
