//
//  Menu2Interactor.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 8/15/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Menu2BusinessLogic
{
  func doSomething(request: Menu2.Something.Request)
}

protocol Menu2DataStore
{
  //var name: String { get set }
}

class Menu2Interactor: Menu2BusinessLogic, Menu2DataStore
{
  var presenter: Menu2PresentationLogic?
  var worker: Menu2Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Menu2.Something.Request)
  {
    worker = Menu2Worker()
    worker?.doSomeWork()
    
    let response = Menu2.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
