//
//  Menu2Presenter.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 8/15/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Menu2PresentationLogic
{
  func presentSomething(response: Menu2.Something.Response)
}

class Menu2Presenter: Menu2PresentationLogic
{
  weak var viewController: Menu2DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Menu2.Something.Response)
  {
    let viewModel = Menu2.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
