//
//  Menu2Worker.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 8/15/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class Menu2Worker
{
  func doSomeWork()
  {
  }
}
