//
//  Menu2Router.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 8/15/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol Menu2RoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol Menu2DataPassing
{
  var dataStore: Menu2DataStore? { get }
}

class Menu2Router: NSObject, Menu2RoutingLogic, Menu2DataPassing
{
  weak var viewController: Menu2ViewController?
  var dataStore: Menu2DataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: Menu2ViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: Menu2DataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
