//
//  ObjectifCataloguePresenter.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 18/11/2020.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ObjectifCataloguePresentationLogic
{
  func presentSomething(response: ObjectifCatalogue.Something.Response)
}

class ObjectifCataloguePresenter: ObjectifCataloguePresentationLogic
{
  weak var viewController: ObjectifCatalogueDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ObjectifCatalogue.Something.Response)
  {
    let viewModel = ObjectifCatalogue.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
