//
//  ObjectifCatalogueViewController.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 18/11/2020.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ObjectifCatalogueDisplayLogic: class
{
    func displaySomething(viewModel: ObjectifCatalogue.Something.ViewModel)
    func setLabel(label : String)
}

class ObjectifCatalogueViewController: UIViewController, ObjectifCatalogueDisplayLogic
{
    
    
    
    
    
    @IBOutlet weak var objectifLabel: UILabel!
    
    
    
    var interactor: ObjectifCatalogueBusinessLogic?
    var router: (NSObjectProtocol & ObjectifCatalogueRoutingLogic & ObjectifCatalogueDataPassing)?
    var objectifTextArea : String = ""
    // MARK: Object lifecycle
    
    
    
    
    
    
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = ObjectifCatalogueInteractor()
        let presenter = ObjectifCataloguePresenter()
        let router = ObjectifCatalogueRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomething()
        objectifLabel.text = "3assba "
        
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = ObjectifCatalogue.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: ObjectifCatalogue.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
    
    func setLabel(label : String){
        print(label)
        print("www")
        print(self.objectifLabel.text)
    }
    
    
}

