//
//  ObjectifCatalogueInteractor.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 18/11/2020.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ObjectifCatalogueBusinessLogic
{
  func doSomething(request: ObjectifCatalogue.Something.Request)
}

protocol ObjectifCatalogueDataStore
{
  //var name: String { get set }
}

class ObjectifCatalogueInteractor: ObjectifCatalogueBusinessLogic, ObjectifCatalogueDataStore
{
  var presenter: ObjectifCataloguePresentationLogic?
  var worker: ObjectifCatalogueWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ObjectifCatalogue.Something.Request)
  {
    worker = ObjectifCatalogueWorker()
    worker?.doSomeWork()
    
    let response = ObjectifCatalogue.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
