//
//  FormateurCatalogueFormationInteractor.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 5/19/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FormateurCatalogueFormationBusinessLogic
{
  func doSomething(request: FormateurCatalogueFormation.Something.Request)
}

protocol FormateurCatalogueFormationDataStore
{
  //var name: String { get set }
}

class FormateurCatalogueFormationInteractor: FormateurCatalogueFormationBusinessLogic, FormateurCatalogueFormationDataStore
{
  var presenter: FormateurCatalogueFormationPresentationLogic?
  var worker: FormateurCatalogueFormationWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: FormateurCatalogueFormation.Something.Request)
  {
    worker = FormateurCatalogueFormationWorker()
    worker?.doSomeWork()
    
    let response = FormateurCatalogueFormation.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
