//
//  FormateurCatalogueFormationPresenter.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 5/19/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FormateurCatalogueFormationPresentationLogic
{
  func presentSomething(response: FormateurCatalogueFormation.Something.Response)
}

class FormateurCatalogueFormationPresenter: FormateurCatalogueFormationPresentationLogic
{
  weak var viewController: FormateurCatalogueFormationDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: FormateurCatalogueFormation.Something.Response)
  {
    let viewModel = FormateurCatalogueFormation.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
