//
//  CatalogueFormationDetailsWorker.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 5/17/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Promise

class CatalogueFormationDetailsWorker
{
    func doSomeWork()
    {
    }
    
    func gettingFormationCatalogueById(token: String, code : String) ->Promise<FormationCatalogueDetails>{
        print("worker formation catalogue Catalogue !")
        return FormationAPI.gettingFormationCatalogueById(token: token, code: code)
    }
    
    func getSkills(token:String)->Promise<[CompetenseLabelResponseElement]>{
        return CompetecenceAPI.showCompetenceLabelCollaborateur(token:token)
    }
    
}
