//
//  MenuFormationPresenter.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 5/12/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MenuFormationPresentationLogic
{
  func presentSomething(response: MenuFormation.Something.Response)
}

class MenuFormationPresenter: MenuFormationPresentationLogic
{
  weak var viewController: MenuFormationDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MenuFormation.Something.Response)
  {
    let viewModel = MenuFormation.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
