//
//  MenuFormationInteractor.swift
//  MakremAccretio
//
//  Created by Makrem chambah on 5/12/20.
//  Copyright (c) 2020 Makrem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MenuFormationBusinessLogic
{
  func doSomething(request: MenuFormation.Something.Request)
}

protocol MenuFormationDataStore
{
  //var name: String { get set }
}

class MenuFormationInteractor: MenuFormationBusinessLogic, MenuFormationDataStore
{
  var presenter: MenuFormationPresentationLogic?
  var worker: MenuFormationWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MenuFormation.Something.Request)
  {
    worker = MenuFormationWorker()
    worker?.doSomeWork()
    
    let response = MenuFormation.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
